### ISSUE TITLE
double message

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#241] opened 2024-03-28 13:51 UTC
![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/8d143858-b015-49cf-a57a-51fd0118a6de)

**Comment by burnout87** [comment] 2024-03-28 14:44
cannot reproduce it, neither locally nor on the staging

**Comment by burnout87** [comment] 2024-03-28 14:57
close it for now, to re-open if it re-appears

**Closed by burnout87** 2024-03-28 14:57 UTC
