### ISSUE TITLE
jemx tab requests isgri insturment

### ISSUE THREAD

**Issue by volodymyrss** [oda-hub/mmoda-frontend-module#219] opened 2023-12-08 14:29 UTC
![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3909535/31020c82-75d6-422f-ae92-e756ab7b6cbf)

**Comment by burnout87** [comment] 2023-12-12 16:56
At the moment, I can not reproduce the issue

**Comment by volodymyrss** [comment] 2023-12-13 08:27
Could you anyway look into why this might happen, and also why the module code is different between jemx and isgri?

**Comment by motame** [comment] 2023-12-13 14:13
The same on my side, can not reproduce !
![chrome_4KkWaNjnuT](https://github.com/oda-hub/mmoda-frontend-module/assets/44972498/a464f6a8-426e-4bfd-88bc-946b478861b4)

**Comment by burnout87** [comment] 2023-12-19 13:32
Finally I managed to reproduce it! I am trying to figure in which specific circumstances it happens

**Comment by burnout87** [comment] 2023-12-19 17:58
While attempting to reproduce the issue, I spotted also this, and it is related in a way.

![image](https://github.com/oda-hub/mmoda-frontend-module/assets/3757833/4b70bf4f-03f9-49d3-baa3-cab2c9a08565)

**Comment by burnout87** [comment] 2024-01-03 11:06
It's quite unclear on why it happens, and inconsistent.

It seems like the instrument name remains set to the value of the one for which previously one request was sent. But I don't understand why that happens.

In any case I propose this change to make sure the instrument name is set to the correct one

https://github.com/oda-hub/mmoda-frontend-module/pull/221

**Comment by motame** [comment] 2024-01-05 17:54
This is another issue that I'm not able to reproduce.
Would you please describe how to land in such a situation ?

**Comment by motame** [comment] 2024-01-05 17:58
I had to edit the html to reproduce it.
Removed manually checked="checked" and here is the result ...

![firefox_V694k4K2Ni](https://github.com/oda-hub/mmoda-frontend-module/assets/44972498/2953d696-0373-4094-8a55-ca2db1265d5f)

**Comment by motame** [comment] 2024-01-05 18:03
And even if it happens, I guess it's another issue that should be tackled in a separate ticket.

**Comment by burnout87** [comment] 2024-01-05 18:07
> And even if it happens, I guess it's another issue that should be tackled in a separate ticket.

yes that is another issue, but I noticed (only twice) when that happens, then the error of this issue is reproduced...

**Comment by burnout87** [comment] 2024-01-05 18:09
> This is another issue that I'm not able to reproduce. Would you please describe how to land in such a situation ?

This is the real issue here, it's not consistently reproducible...this time it happened after having completed a dummy spectrum request with isgri, and the moved to the JEMX tab...and I noticed that

**Comment by motame** [comment] 2024-01-05 18:25
Quite strange ! as the forms (one per instrument) are prepared on the server side and the product type is a radio box and one of them is selected (the first one). The JS code is not touching this form element.
It's very difficult for the user to un-select all of them.

**Comment by volodymyrss** [comment] 2024-01-08 08:37
@burnout87 do you have any insight on the conditions in which you saw the issue?

I saw it on attempted production deployment which was rolled-back, so I will not repeat it until we are reasonably sure the problem is not reappearing.
Since these issues appear in other deployments of @burnout87 they are helpful to explore.

We can also look on staging frontend which should be equivalent to coming release https://frontend-staging.obsuks1.unige.ch/ I will check why it seems currently not quite accessible.

**Comment by burnout87** [comment] 2024-01-08 09:56
> @burnout87 do you have any insight on the conditions in which you saw the issue?
> 

unfortunately this is really not clear, every time I reproduced the error, my sequence of interactions with the frontend was different

> I saw it on attempted production deployment which was rolled-back, so I will not repeat it until we are reasonably sure the problem is not reappearing. Since these issues appear in other deployments of @burnout87 they are helpful to explore.
> 

I managed to reproduce twice also on my local instance (which atm only has isgri and jemx instruments installed)

**Comment by burnout87** [comment] 2024-01-08 14:38
> While attempting to reproduce the issue, I spotted also this, and I think it is related in a way.
> 
> ![image](https://private-user-images.githubusercontent.com/3757833/291673717-4b70bf4f-03f9-49d3-baa3-cab2c9a08565.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0NzgyNzQsIm5iZiI6MTcwNDQ3Nzk3NCwicGF0aCI6Ii8zNzU3ODMzLzI5MTY3MzcxNy00YjcwYmY0Zi0wM2Y5LTQ5ZDMtYmFhMy1jYWIyYzlhMDg1NjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDVUMTgwNjE0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YzRmZDY4MzczNjkzMGEwNGE5NWFjNzFjMGQ5NzE4MDg1YmZkOTAxM2ZmZTRhYTE1ODMzNzQ2MzhkYTQ0Njg2MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.BqrNu3aL74dmyAM2OS5M5gghHQ2IGhODd81W1YxIvlU)

While investigating, I think I figured where this comes from, and it's not related to the original problem of this issue, rather to: #222

**Comment by volodymyrss** [comment] 2024-01-09 14:44
we also see this on production now, a kind of a race conditio

**Comment by volodymyrss** [comment] 2024-01-15 09:15
@motame says the ajax call is not properly cancelled.
@motame confirms it's reproduced in chrome and firefox
@volodymyrss observes more critical issue likely related to the same base issue

**Comment by burnout87** [comment] 2024-01-22 08:26
I noticed that during the preparation of the form before submit, the instrument value (extract from hidden input param of the form itself) remains set to the value of the previous instrument for which a request was sent and not completed.

EG 
1. first request interrupted with `jemx`
2. second request with `spi-acs` results in the instrument still being set to `jemx`
3. error for unavailable product type for a certain instrument is returned from the dispatcher

Therefor, I suggest to extract the instrument name from the form_id itself :

https://github.com/oda-hub/mmoda-frontend-module/pull/226

**Comment by volodymyrss** [comment] 2024-01-22 09:28
> I noticed that during the preparation of the form before submit, the instrument value (extract from hidden input param of the form itself) remains set to the value of the previous instrument for which a request was sent and not completed.
> 
> EG
> 
>     1. first request interrupted with `jemx`
> 
>     2. second request with `spi-acs` results in the instrument still being set to `jemx`
> 
>     3. error for unavailable product type for a certain instrument is returned from the dispatcher
> 
> 
> Therefor, I suggest to extract the instrument name from the form_id itself :
> 
> #226

This sounds like something I saw.

**Comment by motame** [comment] 2024-01-26 09:39
@volodymyrss, is there a test instance, a kind of pre-prod instance where we see the latest from GitHub.
Tests will be much more effective (identical env as prod) than on our dev instances.

**Comment by motame** [comment] 2024-01-26 09:47
Would you please try to reproduce on https://cdcidev.mtmco.net/mmoda/ ?

**Comment by motame** [comment] 2024-01-28 16:19
Yes, yes, sorry ! I was exploring many tracks and then it was not stable at all.
I'll move it to a separate test instance soon.

**Comment by volodymyrss** [comment] 2024-01-28 16:38
> Yes, yes, sorry ! I was exploring many tracks and then it was not stable at all. I'll move it to a separate test instance soon.

Alright, please let me know when I can try to reproduce it!

**Comment by motame** [comment] 2024-01-29 15:23
Here is the test instance that won't be touched :-) unless I inform you !:
https://test.mtmco.net/mmoda/

**Comment by volodymyrss** [comment] 2024-01-30 08:29
> Here is the test instance that won't be touched :-) unless I inform you !: https://test.mtmco.net/mmoda/

I think it's ok now, I can not see the issue anymore, thanks!
Let me know if when it's in the module repo.

**Comment by volodymyrss** [comment] 2024-01-30 10:55
something similar happened for resolve, also fixed

**Comment by motame** [comment] 2024-01-31 10:49
Code pushed to GitHub with other consistent components, [mmoda-frontend-drupal](https://github.com/oda-hub/mmoda-frontend-drupal), [mmoda-frontend-db](https://github.com/oda-hub/mmoda-frontend-db) and [mmoda-frontend-theme](https://github.com/oda-hub/mmoda-frontend-theme)

**Comment by dsavchenko** [comment] 2024-02-12 09:32
I see very weird issues in the Sentry for the French staging `product type mosaic not in query_dictionary {'spi_acs_lc': 'spi_acs_lc_query'}` as well as `product type model_CTA_events not in query_dictionary {'spi_acs_lc': 'spi_acs_lc_query'}` etc.

Probably related

**Comment by volodymyrss** [comment] 2024-02-12 09:34
Yes, I also just saw it in staging.odahub.fr . Did you deploy the latest frontend? I thought @motame fixed it? Maybe not.

**Comment by motame** [comment] 2024-02-12 09:37
> I see very weird issues in the Sentry for the French staging `product type mosaic not in query_dictionary {'spi_acs_lc': 'spi_acs_lc_query'}` as well as `product type model_CTA_events not in query_dictionary {'spi_acs_lc': 'spi_acs_lc_query'}` etc.
> 
> Probably related

Would you please elaborate ...
What was your initial request, instrument ?

**Comment by dsavchenko** [comment] 2024-02-12 09:44
> Would you please elaborate ...
> What was your initial request, instrument ?

I don't know, this is not me who intended to request something, I only see the logs. 


> Did you deploy the latest frontend?

Yes. I deployed the container, which I had built with the current master of mmoda drupal module (available as frodahub/frontend:023aa6fb).

**Comment by volodymyrss** [comment] 2024-03-04 10:45
[this comment](https://github.com/oda-hub/mmoda-frontend-module/issues/222#issuecomment-1973467248) belong here

**Comment by dsavchenko** [comment] 2024-03-21 13:33
@okolo got it on staging

> I just tried to run model_CTA_events job on ODA staging. When I open the link, which I received by email it shows strange error message "Error 400, : [ InstrumentQueryBackEnd : agn_cacades ] constructor failed: product type model_CTA_events not in query_dictionary {'Simulate': 'Simulate_query'}" It looks like it tries to open agn_cacades instrument instead of CTA.

**Comment by motame** [comment] 2024-03-21 13:49
> @okolo got it on staging
> 
> > I just tried to run model_CTA_events job on ODA staging. When I open the link, which I received by email it shows strange error message "Error 400, : [ InstrumentQueryBackEnd : agn_cacades ] constructor failed: product type model_CTA_events not in query_dictionary {'Simulate': 'Simulate_query'}" It looks like it tries to open agn_cacades instrument instead of CTA.
> 
> Note that agn_cascades is currently the first tab

OK but it's still happening when opening a link.

**Comment by motame** [comment] 2024-03-22 14:39
Requests with URLs have been broken by a previous fix of this issue.
The requests with URLs are now fixed and another fix has been found and applied for requests directly via the web site.

**Closed** 2024-03-28 13:54 UTC
Labels: bug, coming-release
